-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "domain_search_terms" (
	"id" serial PRIMARY KEY NOT NULL,
	"domain" text NOT NULL,
	"search_term" text NOT NULL,
	"first_seen" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "seo_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"domain" text NOT NULL,
	"analyzed_at" timestamp DEFAULT now() NOT NULL,
	"overall_score" real,
	"lighthouse_performance" real,
	"lighthouse_accessibility" real,
	"lighthouse_best_practices" real,
	"lighthouse_seo" real,
	"lcp" real,
	"cls" real,
	"inp" real,
	"fcp" real,
	"ttfb" real,
	"technical_seo_score" real,
	"has_title" boolean,
	"title_content" text,
	"has_meta_description" boolean,
	"meta_description_content" text,
	"has_canonical" boolean,
	"canonical_url" text,
	"has_robots_txt" boolean,
	"has_sitemap_xml" boolean,
	"sitemap_url" text,
	"has_hreflang" boolean,
	"has_structured_data" boolean,
	"structured_data_types" jsonb,
	"security_score" real,
	"is_https" boolean,
	"ssl_valid" boolean,
	"ssl_expiry_days" integer,
	"has_hsts" boolean,
	"has_csp" boolean,
	"has_x_frame_options" boolean,
	"has_x_content_type_options" boolean,
	"security_headers" jsonb,
	"content_quality_score" real,
	"word_count" integer,
	"has_h1" boolean,
	"h1_count" integer,
	"h2_count" integer,
	"image_count" integer,
	"images_with_alt" integer,
	"alt_text_coverage" real,
	"internal_link_count" integer,
	"external_link_count" integer,
	"mobile_readiness_score" real,
	"has_viewport_meta" boolean,
	"viewport_content" text,
	"is_mobile_responsive" boolean,
	"international_seo_score" real,
	"detected_language" text,
	"has_charset_declaration" boolean,
	"charset_value" text,
	"hreflang_tags" jsonb,
	"has_english_version" boolean,
	"trust_signals_score" real,
	"has_contact_page" boolean,
	"contact_page_url" text,
	"has_social_links" boolean,
	"social_links_found" jsonb,
	"has_certification_mentions" boolean,
	"certifications_found" jsonb,
	"has_privacy_policy" boolean,
	"has_terms_of_service" boolean,
	"markdown_report" text NOT NULL,
	"analysis_error" text,
	"analysis_successful" boolean DEFAULT false NOT NULL,
	"social_preview_score" real,
	"og_title" text,
	"og_description" text,
	"og_image" text,
	"og_image_is_absolute" boolean,
	"twitter_card" text,
	"social_preview_issues" jsonb,
	"image_optimization_score" real,
	"total_images" integer,
	"modern_format_count" integer,
	"modern_format_percent" real,
	"lazy_loaded_count" integer,
	"missing_lazy_load" integer,
	"above_fold_lazy_loaded" integer,
	"missing_dimensions" integer,
	"broken_images" jsonb,
	"responsive_images" integer,
	"link_health_score" real,
	"total_internal_links" integer,
	"total_external_links" integer,
	"broken_internal_links_count" integer,
	"broken_external_links_count" integer,
	"broken_internal_links" jsonb,
	"broken_external_links" jsonb,
	"redirect_chains_count" integer,
	"nofollow_links" integer,
	"generic_anchors" integer,
	"schema_analysis_score" real,
	"schemas_found" jsonb,
	"total_schemas" integer,
	"has_breadcrumbs" boolean,
	"has_organization" boolean,
	"has_faq" boolean,
	"has_article" boolean,
	"has_product" boolean,
	"has_local_business" boolean,
	"has_how_to" boolean,
	"domain_info_score" real,
	"domain_age" real,
	"domain_creation_date" text,
	"domain_expiry_date" text,
	"days_until_expiry" integer,
	"registrar" text,
	"is_expiring_soon" boolean,
	"ssl_grade_score" real,
	"ssl_grade" text,
	"ssl_protocols" jsonb,
	"ssl_vulnerabilities" jsonb,
	"ssl_chain_issues" jsonb,
	"safe_browsing_score" real,
	"is_safe" boolean,
	"threat_types" jsonb,
	"title_length" integer,
	"title_too_long" boolean,
	"description_length" integer,
	"description_too_long" boolean,
	"meta_robots" text,
	"is_no_index" boolean,
	"is_no_follow" boolean,
	"heading_hierarchy_valid" boolean,
	"heading_hierarchy_issues" jsonb,
	"h3_count" integer,
	"h4_count" integer,
	"h5_count" integer,
	"h6_count" integer,
	"readability_score" real,
	"readability_grade" text,
	"paragraph_count" integer,
	"avg_paragraph_length" real,
	"sentence_count" integer,
	"avg_sentence_length" real,
	"list_count" integer,
	"table_count" integer,
	"video_count" integer,
	"iframe_count" integer,
	"has_faq_section" boolean,
	"has_table_of_contents" boolean,
	"analyzer_errors" jsonb
);
--> statement-breakpoint
CREATE TABLE "domains" (
	"id" serial PRIMARY KEY NOT NULL,
	"domain" text NOT NULL,
	"search_query_used" text NOT NULL,
	"industry" text,
	"first_seen" timestamp DEFAULT now() NOT NULL,
	"form_found" boolean,
	"submitted" boolean DEFAULT false,
	"message_type" text,
	"contact_attempt_date" timestamp,
	"contact_email" text,
	"contact_phone" text,
	CONSTRAINT "domains_domain_unique" UNIQUE("domain")
);
--> statement-breakpoint
ALTER TABLE "domain_search_terms" ADD CONSTRAINT "domain_search_terms_domain_domains_domain_fk" FOREIGN KEY ("domain") REFERENCES "public"."domains"("domain") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seo_reports" ADD CONSTRAINT "seo_reports_domain_domains_domain_fk" FOREIGN KEY ("domain") REFERENCES "public"."domains"("domain") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_search_term_domain" ON "domain_search_terms" USING btree ("domain" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "unique_domain_search_term" ON "domain_search_terms" USING btree ("domain" text_ops,"search_term" text_ops);--> statement-breakpoint
CREATE INDEX "idx_seo_report_analyzed_at" ON "seo_reports" USING btree ("analyzed_at" timestamp_ops);--> statement-breakpoint
CREATE INDEX "idx_seo_report_domain" ON "seo_reports" USING btree ("domain" text_ops);--> statement-breakpoint
CREATE INDEX "idx_seo_report_overall_score" ON "seo_reports" USING btree ("overall_score" float4_ops);--> statement-breakpoint
CREATE INDEX "idx_domain" ON "domains" USING btree ("domain" text_ops);--> statement-breakpoint
CREATE INDEX "idx_message_type" ON "domains" USING btree ("message_type" text_ops);--> statement-breakpoint
CREATE INDEX "idx_submitted" ON "domains" USING btree ("submitted" bool_ops);
*/