import { getSeoReportById, getSeoReportByUrlHash } from "@/db/queries"
import { notFound } from "next/navigation"
import Link from "next/link"
import MarkdownContent from "@/components/MarkdownContent"
import HowWeHelp from "@/components/HowWeHelp"
import FloatingFixButton from "@/components/FloatingFixButton"
import DownloadPDFButton from "@/components/DownloadPDFButton"
import FoundedBy from "@/components/FoundedBy"
import ReadyToTalk from "@/components/ReadyToTalk"

interface PageProps {
    params: Promise<{ hash: string }>
}

export default async function ReportDetailPage({ params }: PageProps) {
    const { hash } = await params

    // Use the hash directly from the URL
    // Example: "mxkDJoBs78Q8"
    const urlHash = hash

    if (!urlHash) {
        console.error("❌ Hash is missing from URL:", hash)
        notFound()
    }

    // Step 1: Find the report by url_hash to get its ID
    const reportByHash = await getSeoReportByUrlHash(urlHash)

    if (!reportByHash || !reportByHash.id) {
        console.error("❌ Report not found for hash:", urlHash)
        console.error("   Searched in database for url_hash =", urlHash)
        notFound()
    }

    // Step 2: Get the full report by ID (like we did before)
    const report = await getSeoReportById(reportByHash.id)

    if (!report) {
        console.error("❌ Report not found for ID:", reportByHash.id)
        notFound()
    }

    return (
        <div className="bg-background text-text min-h-screen">
            <div className="mx-auto max-w-7xl p-8">
                <div className="mb-4">
                    <Link
                        href="/reports"
                        className="no-print inline-block text-blue-600 hover:underline"
                    >
                        ← Back to Reports
                    </Link>
                </div>

                {/* Report generated by - Top */}
                <div className="mb-6 text-center text-2xl font-semibold text-gray-700">
                    Report generated by www.pixaventures.com
                </div>

                <h1 className="mb-2 text-4xl font-bold text-gray-900">{report.domain}</h1>
                <p className="mb-8 text-gray-600 text-lg">
                    Analyzed:{" "}
                    {report.analyzedAt instanceof Date
                        ? report.analyzedAt.toLocaleString()
                        : new Date(
                            report.analyzedAt as unknown as string
                        ).toLocaleString()}
                </p>

                {report.overallScore !== null && (
                    <div className="mb-8 rounded-lg bg-linear-to-br from-blue-50 to-indigo-50 p-8 border border-blue-200 shadow-sm">
                        <h2 className="mb-2 text-2xl font-semibold text-gray-800">
                            Overall SEO Score
                        </h2>
                        <div className="flex items-baseline gap-3">
                            <div className="text-6xl font-bold text-blue-600">
                                {Math.round(report.overallScore)}
                            </div>
                            <div className="text-2xl text-gray-500">/ 100</div>
                        </div>
                        <p className="mt-4 text-sm text-gray-600">
                            {report.overallScore >= 90
                                ? "Excellent - Your website is performing exceptionally well!"
                                : report.overallScore >= 70
                                    ? "Good - Your website is performing well with room for improvement."
                                    : report.overallScore >= 50
                                        ? "Needs Improvement - There are several areas that need attention."
                                        : "Poor - Significant improvements are needed to enhance your SEO performance."}
                        </p>
                    </div>
                )}

                <div className="mb-8 grid gap-6 md:grid-cols-2">
                    {/* Lighthouse Scores */}
                    {(report.lighthousePerformance !== null ||
                        report.lighthouseAccessibility !== null ||
                        report.lighthouseBestPractices !== null ||
                        report.lighthouseSeo !== null) && (
                            <div className="rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
                                <h2 className="mb-4 text-xl font-semibold text-gray-800">
                                    Lighthouse Scores
                                </h2>
                                <div className="space-y-3">
                                    {report.lighthousePerformance !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <span className="text-gray-700">Performance:</span>
                                            <div className="flex items-center gap-2">
                                                <div className={`w-16 h-2 rounded-full ${report.lighthousePerformance >= 90 ? 'bg-green-500' :
                                                    report.lighthousePerformance >= 50 ? 'bg-yellow-500' :
                                                        'bg-red-500'
                                                    }`} style={{ width: `${report.lighthousePerformance}px` }}></div>
                                                <span className="font-semibold text-gray-900 min-w-[3rem] text-right">
                                                    {Math.round(report.lighthousePerformance)}/100
                                                </span>
                                            </div>
                                        </div>
                                    )}
                                    {report.lighthouseAccessibility !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <span className="text-gray-700">Accessibility:</span>
                                            <div className="flex items-center gap-2">
                                                <div className={`w-16 h-2 rounded-full ${report.lighthouseAccessibility >= 90 ? 'bg-green-500' :
                                                    report.lighthouseAccessibility >= 50 ? 'bg-yellow-500' :
                                                        'bg-red-500'
                                                    }`} style={{ width: `${report.lighthouseAccessibility}px` }}></div>
                                                <span className="font-semibold text-gray-900 min-w-[3rem] text-right">
                                                    {Math.round(report.lighthouseAccessibility)}/100
                                                </span>
                                            </div>
                                        </div>
                                    )}
                                    {report.lighthouseBestPractices !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <span className="text-gray-700">Best Practices:</span>
                                            <div className="flex items-center gap-2">
                                                <div className={`w-16 h-2 rounded-full ${report.lighthouseBestPractices >= 90 ? 'bg-green-500' :
                                                    report.lighthouseBestPractices >= 50 ? 'bg-yellow-500' :
                                                        'bg-red-500'
                                                    }`} style={{ width: `${report.lighthouseBestPractices}px` }}></div>
                                                <span className="font-semibold text-gray-900 min-w-[3rem] text-right">
                                                    {Math.round(report.lighthouseBestPractices)}/100
                                                </span>
                                            </div>
                                        </div>
                                    )}
                                    {report.lighthouseSeo !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <span className="text-gray-700">SEO:</span>
                                            <div className="flex items-center gap-2">
                                                <div className={`w-16 h-2 rounded-full ${report.lighthouseSeo >= 90 ? 'bg-green-500' :
                                                    report.lighthouseSeo >= 50 ? 'bg-yellow-500' :
                                                        'bg-red-500'
                                                    }`} style={{ width: `${report.lighthouseSeo}px` }}></div>
                                                <span className="font-semibold text-gray-900 min-w-[3rem] text-right">
                                                    {Math.round(report.lighthouseSeo)}/100
                                                </span>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}

                    {/* Core Web Vitals */}
                    {(report.lcp !== null ||
                        report.cls !== null ||
                        report.inp !== null ||
                        report.fcp !== null ||
                        report.ttfb !== null) && (
                            <div className="rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
                                <h2 className="mb-4 text-xl font-semibold text-gray-800">
                                    Core Web Vitals
                                </h2>
                                <p className="mb-4 text-sm text-gray-600">
                                    These metrics measure real-world user experience and directly impact your search rankings.
                                </p>
                                <div className="space-y-3">
                                    {report.lcp !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <div>
                                                <span className="font-medium text-gray-700">LCP (Largest Contentful Paint):</span>
                                                <p className="text-xs text-gray-500">Time to render the largest content element</p>
                                            </div>
                                            <div className="text-right">
                                                <span className={`font-semibold ${report.lcp <= 2.5 ? 'text-green-600' :
                                                    report.lcp <= 4.0 ? 'text-yellow-600' :
                                                        'text-red-600'
                                                    }`}>
                                                    {report.lcp.toFixed(2)}s
                                                </span>
                                                <p className="text-xs text-gray-500">Target: &lt; 2.5s</p>
                                            </div>
                                        </div>
                                    )}
                                    {report.cls !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <div>
                                                <span className="font-medium text-gray-700">CLS (Cumulative Layout Shift):</span>
                                                <p className="text-xs text-gray-500">Visual stability of the page</p>
                                            </div>
                                            <div className="text-right">
                                                <span className={`font-semibold ${report.cls <= 0.1 ? 'text-green-600' :
                                                    report.cls <= 0.25 ? 'text-yellow-600' :
                                                        'text-red-600'
                                                    }`}>
                                                    {report.cls.toFixed(3)}
                                                </span>
                                                <p className="text-xs text-gray-500">Target: &lt; 0.1</p>
                                            </div>
                                        </div>
                                    )}
                                    {report.inp !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <div>
                                                <span className="font-medium text-gray-700">INP (Interaction to Next Paint):</span>
                                                <p className="text-xs text-gray-500">Responsiveness to user interactions</p>
                                            </div>
                                            <div className="text-right">
                                                <span className={`font-semibold ${report.inp <= 200 ? 'text-green-600' :
                                                    report.inp <= 500 ? 'text-yellow-600' :
                                                        'text-red-600'
                                                    }`}>
                                                    {report.inp.toFixed(0)}ms
                                                </span>
                                                <p className="text-xs text-gray-500">Target: &lt; 200ms</p>
                                            </div>
                                        </div>
                                    )}
                                    {report.fcp !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <div>
                                                <span className="font-medium text-gray-700">FCP (First Contentful Paint):</span>
                                                <p className="text-xs text-gray-500">Time to first content render</p>
                                            </div>
                                            <div className="text-right">
                                                <span className={`font-semibold ${report.fcp <= 1.8 ? 'text-green-600' :
                                                    report.fcp <= 3.0 ? 'text-yellow-600' :
                                                        'text-red-600'
                                                    }`}>
                                                    {report.fcp.toFixed(2)}s
                                                </span>
                                                <p className="text-xs text-gray-500">Target: &lt; 1.8s</p>
                                            </div>
                                        </div>
                                    )}
                                    {report.ttfb !== null && (
                                        <div className="flex justify-between items-center py-2 border-b border-gray-100 last:border-0">
                                            <div>
                                                <span className="font-medium text-gray-700">TTFB (Time to First Byte):</span>
                                                <p className="text-xs text-gray-500">Server response time</p>
                                            </div>
                                            <div className="text-right">
                                                <span className={`font-semibold ${report.ttfb <= 800 ? 'text-green-600' :
                                                    report.ttfb <= 1800 ? 'text-yellow-600' :
                                                        'text-red-600'
                                                    }`}>
                                                    {report.ttfb.toFixed(0)}ms
                                                </span>
                                                <p className="text-xs text-gray-500">Target: &lt; 800ms</p>
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        )}

                    {/* Technical SEO */}
                    {report.technicalSeoScore !== null && (
                        <div className="rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
                            <h2 className="mb-2 text-xl font-semibold text-gray-800">
                                Technical SEO
                            </h2>
                            <p className="mb-4 text-sm text-gray-600">
                                Ensures search engines can properly crawl and index your website.
                            </p>
                            <div className="mb-4 flex items-baseline gap-2">
                                <div className={`text-3xl font-bold ${report.technicalSeoScore >= 90 ? 'text-green-600' :
                                    report.technicalSeoScore >= 70 ? 'text-yellow-600' :
                                        'text-red-600'
                                    }`}>
                                    {Math.round(report.technicalSeoScore)}
                                </div>
                                <span className="text-gray-500">/ 100</span>
                            </div>
                            <div className="space-y-3 text-sm">
                                {report.hasTitle !== null && (
                                    <div className="py-2 border-b border-gray-100 last:border-0">
                                        <div className="flex items-start justify-between">
                                            <span className="font-medium text-gray-700">Title Tag:</span>
                                            <span className={report.hasTitle ? "text-green-600 font-semibold" : "text-red-600 font-semibold"}>
                                                {report.hasTitle ? "✓ Present" : "✗ Missing"}
                                            </span>
                                        </div>
                                        {report.titleContent && (
                                            <div className="mt-2 p-2 bg-gray-50 rounded text-gray-700 text-xs">
                                                &ldquo;{report.titleContent}&rdquo;
                                                {report.titleLength && (
                                                    <span className="ml-2 text-gray-500">
                                                        ({report.titleLength} chars{report.titleTooLong ? " - too long!" : ""})
                                                    </span>
                                                )}
                                            </div>
                                        )}
                                    </div>
                                )}
                                {report.hasMetaDescription !== null && (
                                    <div className="py-2 border-b border-gray-100 last:border-0">
                                        <div className="flex items-start justify-between">
                                            <span className="font-medium text-gray-700">Meta Description:</span>
                                            <span className={report.hasMetaDescription ? "text-green-600 font-semibold" : "text-red-600 font-semibold"}>
                                                {report.hasMetaDescription ? "✓ Present" : "✗ Missing"}
                                            </span>
                                        </div>
                                        {report.metaDescriptionContent && (
                                            <div className="mt-2 p-2 bg-gray-50 rounded text-gray-700 text-xs">
                                                &ldquo;{report.metaDescriptionContent}&rdquo;
                                                {report.descriptionLength && (
                                                    <span className="ml-2 text-gray-500">
                                                        ({report.descriptionLength} chars{report.descriptionTooLong ? " - too long!" : ""})
                                                    </span>
                                                )}
                                            </div>
                                        )}
                                    </div>
                                )}
                                {report.hasCanonical !== null && (
                                    <div className="py-2 border-b border-gray-100 last:border-0">
                                        <div className="flex items-start justify-between">
                                            <span className="font-medium text-gray-700">Canonical URL:</span>
                                            <span className={report.hasCanonical ? "text-green-600 font-semibold" : "text-yellow-600 font-semibold"}>
                                                {report.hasCanonical ? "✓ Present" : "✗ Missing"}
                                            </span>
                                        </div>
                                        {report.canonicalUrl && (
                                            <div className="mt-2 p-2 bg-gray-50 rounded text-gray-600 text-xs break-all">
                                                {report.canonicalUrl}
                                            </div>
                                        )}
                                    </div>
                                )}
                                {report.hasRobotsTxt !== null && (
                                    <div className="py-2 border-b border-gray-100 last:border-0">
                                        <div className="flex items-start justify-between">
                                            <span className="font-medium text-gray-700">robots.txt:</span>
                                            <span className={report.hasRobotsTxt ? "text-green-600 font-semibold" : "text-yellow-600 font-semibold"}>
                                                {report.hasRobotsTxt ? "✓ Present" : "✗ Missing"}
                                            </span>
                                        </div>
                                    </div>
                                )}
                                {report.hasSitemapXml !== null && (
                                    <div className="py-2 border-b border-gray-100 last:border-0">
                                        <div className="flex items-start justify-between">
                                            <span className="font-medium text-gray-700">Sitemap:</span>
                                            <span className={report.hasSitemapXml ? "text-green-600 font-semibold" : "text-yellow-600 font-semibold"}>
                                                {report.hasSitemapXml ? "✓ Present" : "✗ Missing"}
                                            </span>
                                        </div>
                                        {report.sitemapUrl && (
                                            <div className="mt-2 p-2 bg-gray-50 rounded text-gray-600 text-xs break-all">
                                                {report.sitemapUrl}
                                            </div>
                                        )}
                                    </div>
                                )}
                            </div>
                        </div>
                    )}

                    {/* Security */}
                    {report.securityScore !== null && (
                        <div className="rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
                            <h2 className="mb-2 text-xl font-semibold text-gray-800">
                                Security
                            </h2>
                            <p className="mb-4 text-sm text-gray-600">
                                Security measures protect your visitors and build trust with both users and search engines.
                            </p>
                            <div className="mb-4 flex items-baseline gap-2">
                                <div className={`text-3xl font-bold ${report.securityScore >= 90 ? 'text-green-600' :
                                    report.securityScore >= 70 ? 'text-yellow-600' :
                                        'text-red-600'
                                    }`}>
                                    {Math.round(report.securityScore)}
                                </div>
                                <span className="text-gray-500">/ 100</span>
                            </div>
                            <div className="space-y-3 text-sm">
                                {report.isHttps !== null && (
                                    <div className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                                        <span className="font-medium text-gray-700">HTTPS:</span>
                                        <span className={report.isHttps ? "text-green-600 font-semibold" : "text-red-600 font-semibold"}>
                                            {report.isHttps ? "✓ Enabled" : "✗ Not Enabled"}
                                        </span>
                                    </div>
                                )}
                                {report.sslValid !== null && (
                                    <div className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                                        <span className="font-medium text-gray-700">SSL Valid:</span>
                                        <span className={report.sslValid ? "text-green-600 font-semibold" : "text-red-600 font-semibold"}>
                                            {report.sslValid ? "✓ Valid" : "✗ Invalid"}
                                        </span>
                                    </div>
                                )}
                                {report.hasHsts !== null && (
                                    <div className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                                        <span className="font-medium text-gray-700">HSTS Header:</span>
                                        <span className={report.hasHsts ? "text-green-600 font-semibold" : "text-yellow-600 font-semibold"}>
                                            {report.hasHsts ? "✓ Present" : "✗ Missing"}
                                        </span>
                                    </div>
                                )}
                                {report.hasCsp !== null && (
                                    <div className="flex items-center justify-between py-2 border-b border-gray-100 last:border-0">
                                        <span className="font-medium text-gray-700">Content Security Policy:</span>
                                        <span className={report.hasCsp ? "text-green-600 font-semibold" : "text-yellow-600 font-semibold"}>
                                            {report.hasCsp ? "✓ Present" : "✗ Missing"}
                                        </span>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </div>

                {/* Markdown Report */}
                {report.markdownReport && (
                    <div className="mt-8 rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
                        <h2 className="mb-4 text-xl font-semibold text-gray-800">
                            Detailed Analysis Report
                        </h2>
                        <div className="prose prose-sm max-w-none">
                            <MarkdownContent content={report.markdownReport} />
                        </div>
                    </div>
                )}

                {/* Error Message */}
                {report.analysisError && (
                    <div className="mt-8 rounded-lg border border-red-200 bg-red-50 p-6">
                        <h2 className="mb-2 text-xl font-semibold text-red-800">
                            Analysis Error
                        </h2>
                        <p className="text-red-700">{report.analysisError}</p>
                    </div>
                )}

                {/* Report generated by - Bottom */}
                <div className="mt-8 text-center text-2xl font-semibold text-gray-700">
                    Report generated by www.pixaventures.com
                </div>
            </div>
            <div className="mt-12">
                <HowWeHelp />
                <FoundedBy />
                <ReadyToTalk />
            </div>
            <div className="no-print">
                <FloatingFixButton domain={report.domain} />
                <DownloadPDFButton />
            </div>
        </div>
    )
}
